# Site settings
title: 虫窝 
name: 虫窝
email: wormchaos@126.com
author: wormchaos
url: https://wormchaos.github.io/
#resume_site: https://wormchaos.github.io/Resume.io/
github: https://github.com/wormchaos/
baseurl: ""
description: Actually, less is more!
meta_description: wormchaos;blogs
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wormchaos

# Build settings
markdown: kramdown

baidu_analysis: e411ef0ea7ddb6b188679f8383b5a44b

